"""
identity_consistency_engine.py
--------------------------------
This is Engine 4 itself: it CONSUMES the dataset generated by
generate_dataset.py and runs actual consistency checks on it.

Run order:
  1. python3 generate_dataset.py
  2. python3 identity_consistency_engine.py
"""

import json
from collections import defaultdict
from pathlib import Path

from rapidfuzz import fuzz

DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def load_data():
    with open(DATA_DIR / "persons.json", encoding="utf-8") as f:
        persons = json.load(f)
    with open(DATA_DIR / "documents.json", encoding="utf-8") as f:
        documents = json.load(f)
    with open(DATA_DIR / "ground_truth_labels.json", encoding="utf-8") as f:
        labels = json.load(f)
    return persons, documents, labels


def check_dob_consistency(person, docs):
    findings = []
    dobs = {d["dob_on_doc"] for d in docs}
    if len(dobs) > 1:
        findings.append({
            "check": "dob_consistency",
            "severity": "HIGH",
            "detail": f"Conflicting DOBs across documents: {sorted(dobs)}",
        })
    return findings


def check_name_consistency(person, docs, threshold=80):
    findings = []
    canonical = person["canonical_name_en"]
    for d in docs:
        score = fuzz.token_sort_ratio(canonical, d["name_on_doc"])
        if score < threshold:
            findings.append({
                "check": "name_consistency",
                "severity": "HIGH",
                "detail": f"Name on {d['doc_type']} ('{d['name_on_doc']}') only "
                          f"{score:.0f}% similar to canonical ('{canonical}').",
                "document_id": d["document_id"],
            })
    return findings


def check_transliteration_consistency(person, docs, threshold=70):
    findings = []
    canonical_hi = person["canonical_name_hi"]
    for d in docs:
        name_hi = d.get("name_on_doc_hi")
        if not name_hi:
            continue
        score = fuzz.ratio(canonical_hi, name_hi)
        if score < threshold:
            findings.append({
                "check": "transliteration_consistency",
                "severity": "MEDIUM",
                "detail": f"Hindi name on {d['doc_type']} ('{name_hi}') only "
                          f"{score:.0f}% similar to canonical ('{canonical_hi}').",
                "document_id": d["document_id"],
            })
    return findings


def check_address_consistency(person, docs, threshold=60):
    findings = []
    canonical_addr = person["address"]
    for d in docs:
        score = fuzz.token_sort_ratio(canonical_addr, d["address_on_doc"])
        if score < threshold:
            findings.append({
                "check": "address_consistency",
                "severity": "MEDIUM",
                "detail": f"Address on {d['doc_type']} differs significantly "
                          f"from person record ({score:.0f}% similarity).",
                "document_id": d["document_id"],
            })
    return findings


def check_shared_document_numbers(all_documents):
    by_number = defaultdict(list)
    for d in all_documents:
        by_number[(d["doc_type"], d["document_number"])].append(d)

    findings_by_person = defaultdict(list)
    for (doc_type, number), docs in by_number.items():
        owners = {d["person_id"] for d in docs}
        if len(owners) > 1:
            for d in docs:
                findings_by_person[d["person_id"]].append({
                    "check": "shared_document_number",
                    "severity": "CRITICAL",
                    "detail": f"{doc_type} number {number} is also used by "
                              f"{len(owners) - 1} other person(s): "
                              f"{sorted(owners - {d['person_id']})}",
                    "document_id": d["document_id"],
                })
    return findings_by_person


SEVERITY_WEIGHT = {"CRITICAL": 40, "HIGH": 25, "MEDIUM": 10, "LOW": 5}

def score_person(findings):
    score = sum(SEVERITY_WEIGHT.get(f["severity"], 0) for f in findings)
    score = min(score, 100)
    if score >= 40:
        level = "HIGH"
    elif score >= 15:
        level = "MEDIUM"
    elif score > 0:
        level = "LOW"
    else:
        level = "NONE"
    return score, level


def run_engine():
    persons, documents, gt_labels = load_data()

    docs_by_person = defaultdict(list)
    for d in documents:
        docs_by_person[d["person_id"]].append(d)

    shared_number_findings = check_shared_document_numbers(documents)

    report = []
    for person in persons:
        pid = person["person_id"]
        docs = docs_by_person[pid]

        findings = []
        findings += check_dob_consistency(person, docs)
        findings += check_name_consistency(person, docs)
        findings += check_transliteration_consistency(person, docs)
        findings += check_address_consistency(person, docs)
        findings += shared_number_findings.get(pid, [])

        score, level = score_person(findings)

        report.append({
            "person_id": pid,
            "canonical_name_en": person["canonical_name_en"],
            "risk_score": score,
            "risk_level": level,
            "findings": findings,
            "ground_truth_is_anomalous": person["is_anomalous"],
        })

    with open(DATA_DIR / "consistency_report.json", "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)

    evaluate(report)
    return report


def evaluate(report):
    tp = fp = fn = tn = 0
    for r in report:
        predicted_flag = r["risk_level"] != "NONE"
        actual_flag = r["ground_truth_is_anomalous"]
        if predicted_flag and actual_flag:
            tp += 1
        elif predicted_flag and not actual_flag:
            fp += 1
        elif not predicted_flag and actual_flag:
            fn += 1
        else:
            tn += 1

    precision = tp / (tp + fp) if (tp + fp) else 0
    recall = tp / (tp + fn) if (tp + fn) else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0

    print("=" * 60)
    print("IDENTITY CONSISTENCY ENGINE -- EVALUATION")
    print("=" * 60)
    print(f"True Positives  (correctly flagged anomalies): {tp}")
    print(f"False Positives (wrongly flagged genuine):      {fp}")
    print(f"False Negatives (missed anomalies):              {fn}")
    print(f"True Negatives  (correctly passed genuine):      {tn}")
    print("-" * 60)
    print(f"Precision: {precision:.2%}")
    print(f"Recall:    {recall:.2%}")
    print(f"F1 Score:  {f1:.2%}")
    print("=" * 60)
    print("Full per-person report written to: data/consistency_report.json")


if __name__ == "__main__":
    run_engine()